apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-terraform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-terraform-app
  template:
    metadata:
      labels:
        app: aks-terraform-app
    spec:
      containers:
        - name: app
          image: d4ar011.azurecr.io/aks-terraform-app:latest
          ports:
            - containerPort: 3000
